version: "3.9"

services:
  meilisearch:
    image: getmeili/meilisearch:v1.13
    ports:
      - "7700:7700"
    environment:
      - MEILI_ENV=${MEILI_ENV}
    volumes:
      - meili_data:/meili_data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7700/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  data-splitter:
    build:
      context: ./data-splitter
      dockerfile: Dockerfile
    volumes:
      - ./dataset:/app/dataset
    env_file:
      - .env
    depends_on:
      meilisearch:
        condition: service_healthy

  indexer:
    build:
      context: ./indexer
      dockerfile: Dockerfile
    volumes:
      - ./dataset:/app/dataset
    env_file:
      - .env
    depends_on:
      data-splitter:
        condition: service_completed_successfully
      meilisearch:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      indexer:
        condition: service_completed_successfully
      meilisearch:
        condition: service_healthy

volumes:
  meili_data:
